apiVersion: v1
kind: Secret
metadata:
  name: post-service-secret
type: Opaque
data:
  MYSQL_DATASOURCE: amRiYzpteXNxbDovL2t3ZXR0ZXIubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29tOjMzMDYvX3NlcnZpY2U/dXNlU1NMPWZhbHNlJmFsbG93UHVibGljS2V5UmV0cmlldmFsPXRydWU=
  MYSQL_USER: a3dldHRlcg==
  MYSQL_PASSWORD: RzcjWTRVeENzZG5nTGVtJQ==
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=