apiVersion: v1
kind: Secret
metadata:
  name: post-service-secret
type: Opaque
data:
  MYSQL_DATASOURCE: amRiYzpteXNxbDovL2t3ZXR0ZXIubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29tOjMzMDYvcG9zdF9zZXJ2aWNlP3VzZVNTTD1mYWxzZQ
  MYSQL_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=